[files]
extend-exclude = [
    "actionbook/",
    "agent-browser/",
    "conventional-commits/",
    "electron/",
    "exe.dev/",
    "longbridge/",
    "skill-creator/",
    "skillshare/",
    "stl/",
    "tigris-bucket-management/",
    "tigris-object-operations/",
    "tigris-snapshots-forking/",
    "tigris-snapshots-recovery/",
    "xurl/",
]

[default.extend-words]
UDID = "UDID"  # Apple Unique Device Identifier
