#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["typer>=0.26.7"]
# ///
"""Build a local artifact package zip for Oracle/ChatGPT consultation."""

from __future__ import annotations

import os
import shutil
import stat
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Annotated

import typer

PROMPT_NAME = "AGENTS.md"
DEFAULT_OUTPUT_DIR = Path(tempfile.gettempdir()) / "oracle-work"


def fail(message: str) -> None:
    typer.echo(f"artifact-zip: {message}", err=True)
    raise typer.Exit(1)


def safe_name(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in "._-" else "-" for ch in value.strip())
    return cleaned.strip(".-") or "artifact"


def remove_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def copy_file_or_symlink(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() or dest.is_symlink():
        remove_path(dest)
    if src.is_symlink():
        os.symlink(os.readlink(src), dest)
    else:
        shutil.copy2(src, dest)


def copy_tree(src: Path, dest: Path) -> None:
    if src.is_symlink() or src.is_file():
        copy_file_or_symlink(src, dest)
        return
    if not src.is_dir():
        fail(f"not a file or directory: {src}")
    for root, dirs, files in os.walk(src, followlinks=False):
        root_path = Path(root)
        dirs.sort()
        files.sort()
        rel_root = root_path.relative_to(src)
        for dirname in dirs:
            path = root_path / dirname
            if path.is_symlink():
                copy_file_or_symlink(path, dest / rel_root / dirname)
        for filename in files:
            path = root_path / filename
            copy_file_or_symlink(path, dest / rel_root / filename)


def write_agents_prompt(package_path: Path, prompt_md: Path) -> None:
    if not prompt_md.is_file():
        fail(f"prompt Markdown not found: {prompt_md}")
    prompt_text = prompt_md.read_text(encoding="utf-8")
    generated_text = (
        "<!-- Generated by artifact-zip from prompt context. -->\n"
        "# Artifact package instructions\n\n"
        f"{prompt_text.rstrip()}\n\n"
        "---\n\n"
        "# Package layout\n\n"
        "- `artifacts/` contains the local files or directories supplied for this consultation.\n"
        "- `sources.md` lists the package paths and original local filenames captured during packaging.\n"
    )
    (package_path / PROMPT_NAME).write_text(generated_text, encoding="utf-8")


def write_sources(package_path: Path, copied: list[tuple[Path, str]]) -> None:
    lines = ["# Sources", ""]
    for src, dest in copied:
        lines.append(f"- `{dest}` <- local file or directory `{src.name}`")
    lines.append("")
    (package_path / "sources.md").write_text("\n".join(lines), encoding="utf-8")


def zipinfo_for_path(path: Path, arcname: str) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(arcname)
    st = path.lstat()
    info.date_time = datetime.fromtimestamp(st.st_mtime).timetuple()[:6]
    info.external_attr = (st.st_mode & 0xFFFF) << 16
    if path.is_symlink():
        info.external_attr = (stat.S_IFLNK | 0o777) << 16
    return info


def write_zip_entry(zf: zipfile.ZipFile, path: Path, arcname: str) -> None:
    if path.is_symlink():
        zf.writestr(zipinfo_for_path(path, arcname), os.readlink(path).encode())
    elif path.is_file():
        zf.write(path, arcname)
    elif path.is_dir():
        dir_arcname = arcname if arcname.endswith("/") else f"{arcname}/"
        zf.writestr(zipinfo_for_path(path, dir_arcname), b"")


def create_zip(source_root: Path, output_path: Path) -> None:
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        write_zip_entry(zf, source_root, source_root.name)
        for root, dirs, files in os.walk(source_root, followlinks=False):
            root_path = Path(root)
            dirs.sort()
            files.sort()
            for dirname in dirs:
                path = root_path / dirname
                arcname = path.relative_to(source_root.parent).as_posix()
                write_zip_entry(zf, path, arcname)
            for filename in files:
                path = root_path / filename
                arcname = path.relative_to(source_root.parent).as_posix()
                write_zip_entry(zf, path, arcname)


def build_zip(output_dir: Path, prompt_md: Path, name: str, files: list[Path]) -> Path:
    if not files:
        fail("at least one --file is required")

    resolved_output_dir = output_dir.expanduser()
    resolved_output_dir.mkdir(parents=True, exist_ok=True)
    resolved_output_dir = resolved_output_dir.resolve()
    package_name = safe_name(name)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    output_path = resolved_output_dir / f"{package_name}-artifact-package-{stamp}.zip"

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        package_path = tmpdir / f"{package_name}-package"
        artifacts_path = package_path / "artifacts"
        artifacts_path.mkdir(parents=True)

        copied: list[tuple[Path, str]] = []
        used_names: set[str] = set()
        for index, raw_path in enumerate(files, start=1):
            src = raw_path.expanduser().resolve()
            if not src.exists():
                fail(f"file does not exist: {raw_path}")
            base = safe_name(src.name)
            dest_name = base
            if dest_name in used_names:
                dest_name = f"{index:02d}-{base}"
            used_names.add(dest_name)
            dest = artifacts_path / dest_name
            copy_tree(src, dest)
            copied.append((src, f"artifacts/{dest_name}"))

        write_agents_prompt(package_path, prompt_md.expanduser())
        write_sources(package_path, copied)
        create_zip(package_path, output_path)

    return output_path


def main(
    prompt_md: Annotated[
        Path,
        typer.Option("--prompt", help=f"Markdown prompt written to the package root {PROMPT_NAME}."),
    ],
    files: Annotated[
        list[Path],
        typer.Option("--file", "-f", help="Local file or directory to include. Repeat for multiple inputs."),
    ],
    output_dir: Annotated[
        Path,
        typer.Option("--output", "-o", help="Directory where the zip will be written."),
    ] = DEFAULT_OUTPUT_DIR,
    name: Annotated[
        str,
        typer.Option("--name", help="Short package slug used in the zip filename."),
    ] = "oracle",
) -> None:
    output_path = build_zip(output_dir, prompt_md, name, files)
    typer.echo(output_path)


if __name__ == "__main__":
    typer.run(main)
