#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["typer>=0.25.0"]
# ///
"""Build a compact Git repository zip for Oracle/ChatGPT review."""

from __future__ import annotations

import os
import shlex
import shutil
import stat
import subprocess
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Annotated

import typer

PROMPT_NAME = "AGENTS.md"
DEFAULT_OUTPUT_DIR = Path(tempfile.gettempdir()) / "oracle-work"


def fail(message: str) -> None:
    typer.echo(f"repo-zip: {message}", err=True)
    raise typer.Exit(1)


def run_command(args: list[str], cwd: Path | None = None, *, check: bool = True) -> subprocess.CompletedProcess[bytes]:
    proc = subprocess.run(
        args,
        cwd=cwd,
        check=False,
        capture_output=True,
    )
    if check and proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).decode(errors="replace").strip()
        suffix = f"\n{detail}" if detail else ""
        fail(f"command failed ({proc.returncode}): {shlex.join(args)}{suffix}")
    return proc


def run_git(args: list[str], cwd: Path, *, check: bool = True) -> subprocess.CompletedProcess[bytes]:
    return run_command(["git", *args], cwd=cwd, check=check)


def git_text(args: list[str], cwd: Path) -> str:
    return run_git(args, cwd).stdout.decode().strip()


def git_nul_paths(args: list[str], cwd: Path) -> list[str]:
    output = run_git(args, cwd).stdout
    return [os.fsdecode(part) for part in output.split(b"\0") if part]


def safe_branch_name(branch: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "-" for ch in branch)


def remove_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def copy_file_or_symlink(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() or dest.is_symlink():
        remove_path(dest)
    if src.is_symlink():
        os.symlink(os.readlink(src), dest)
    else:
        shutil.copy2(src, dest)


def overlay_worktree_files(repo_root: Path, clone_path: Path) -> None:
    for rel in git_nul_paths(["ls-files", "-z", "--deleted"], repo_root):
        dest = clone_path / rel
        if dest.exists() or dest.is_symlink():
            remove_path(dest)

    paths = git_nul_paths(["ls-files", "-z", "--cached", "--modified", "--others", "--exclude-standard"], repo_root)
    for rel in paths:
        src = repo_root / rel
        # Gitlink entries for submodules are paths in git output, but
        # directories in the source checkout. Copy only files and symlinks so
        # checked-out submodule working trees do not get bundled.
        if src.is_file() or src.is_symlink():
            copy_file_or_symlink(src, clone_path / rel)


def write_agents_prompt(package_path: Path, prompt_md: Path, repo_name: str) -> None:
    if not prompt_md.is_file():
        fail(f"prompt Markdown not found: {prompt_md}")

    prompt_text = prompt_md.read_text(encoding="utf-8")
    target = package_path / PROMPT_NAME
    generated_text = (
        "<!-- Generated by repo-zip from prompt context. -->\n"
        "# Repository package instructions\n\n"
        f"{prompt_text.rstrip()}\n\n"
        "---\n\n"
        "# Package layout\n\n"
        f"- The repository checkout is in `{repo_name}/`.\n"
        f"- The checkout includes `{repo_name}/.git`; use normal git commands from `{repo_name}/` to inspect history, branches, and diffs.\n"
    )
    target.write_text(generated_text, encoding="utf-8")


def zipinfo_for_path(path: Path, arcname: str) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(arcname)
    st = path.lstat()
    info.date_time = datetime.fromtimestamp(st.st_mtime).timetuple()[:6]
    info.external_attr = (st.st_mode & 0xFFFF) << 16
    if path.is_symlink():
        info.external_attr = (stat.S_IFLNK | 0o777) << 16
    return info


def write_zip_entry(zf: zipfile.ZipFile, path: Path, arcname: str) -> None:
    if path.is_symlink():
        zf.writestr(zipinfo_for_path(path, arcname), os.readlink(path).encode())
    elif path.is_file():
        zf.write(path, arcname)
    elif path.is_dir():
        dir_arcname = arcname if arcname.endswith("/") else f"{arcname}/"
        zf.writestr(zipinfo_for_path(path, dir_arcname), b"")


def create_zip(source_root: Path, output_path: Path) -> None:
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        write_zip_entry(zf, source_root, source_root.name)
        for root, dirs, files in os.walk(source_root, followlinks=False):
            root_path = Path(root)
            dirs.sort()
            files.sort()
            for dirname in dirs:
                path = root_path / dirname
                arcname = path.relative_to(source_root.parent).as_posix()
                write_zip_entry(zf, path, arcname)
            for filename in files:
                path = root_path / filename
                arcname = path.relative_to(source_root.parent).as_posix()
                write_zip_entry(zf, path, arcname)


def resolve_repo_root() -> Path:
    proc = run_git(["rev-parse", "--show-toplevel"], Path.cwd(), check=False)
    if proc.returncode != 0:
        fail("not inside a Git repository")
    return Path(proc.stdout.decode().strip())


def build_zip(output_dir: Path, prompt_md: Path) -> Path:
    repo_root = resolve_repo_root()
    repo_name = repo_root.name
    resolved_output_dir = output_dir.expanduser()
    resolved_output_dir.mkdir(parents=True, exist_ok=True)
    resolved_output_dir = resolved_output_dir.resolve()

    current_branch = git_text(["branch", "--show-current"], repo_root)
    head_sha = git_text(["rev-parse", "HEAD"], repo_root)
    branch_label = current_branch or f"detached-{git_text(['rev-parse', '--short', 'HEAD'], repo_root)}"
    safe_branch = safe_branch_name(branch_label)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    output_path = resolved_output_dir / f"{repo_name}-package-{safe_branch}-{stamp}.zip"

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        bundle_path = tmpdir / f"{repo_name}.bundle"
        package_path = tmpdir / f"{repo_name}-package"
        clone_path = package_path / repo_name
        package_path.mkdir()

        run_git(["bundle", "create", str(bundle_path), "--all"], repo_root)
        run_command(["git", "clone", "--quiet", str(bundle_path), str(clone_path)])

        if current_branch:
            probe = run_git(
                ["rev-parse", "--verify", "--quiet", f"refs/heads/{current_branch}"], clone_path, check=False
            )
            if probe.returncode == 0:
                run_git(["checkout", "--quiet", current_branch], clone_path)
            else:
                run_git(["checkout", "--quiet", head_sha], clone_path)
        else:
            run_git(["checkout", "--quiet", head_sha], clone_path)

        overlay_worktree_files(repo_root, clone_path)
        write_agents_prompt(package_path, prompt_md.expanduser(), repo_name)
        create_zip(package_path, output_path)

    return output_path


def main(
    prompt_md: Annotated[
        Path,
        typer.Option("--prompt", help=f"Markdown prompt written to the package root {PROMPT_NAME}."),
    ],
    output_dir: Annotated[
        Path,
        typer.Option("--output", "-o", help="Directory where the zip will be written."),
    ] = DEFAULT_OUTPUT_DIR,
) -> None:
    output_path = build_zip(output_dir, prompt_md)
    typer.echo(output_path)


if __name__ == "__main__":
    typer.run(main)
