[tools]
"github:huacnlee/autocorrect" = "2.16.3"
"github:runkids/skillshare" = "0.20.20"
biome = "2.5.0"
gum = "0.17.0"
jq = "1.8.2"
ls-lint = "2.3.1"
markdownlint-cli2 = "0.22.1"
prek = "0.4.5"
python = "3.14.6"
shellcheck = "0.11.0"
tombi = "1.1.3"
usage = "3.5.2"
uv = "0.11.23"

[env]
_.python.venv = { path = ".venv" }

[settings]
lockfile_platforms = ["macos-arm64", "linux-x64"]

[settings.ruby]
compile = false
