[tools]
"github:huacnlee/autocorrect" = "2.16.3"
"github:runkids/skillshare" = "0.20.9"
biome = "2.4.16"
gum = "0.17.0"
jq = "1.8.1"
ls-lint = "2.3.1"
markdownlint-cli2 = "0.22.1"
prek = "0.4.4"
python = "3.14.5"
shellcheck = "0.11.0"
tombi = "1.1.2"
usage = "3.4.0"
uv = "0.11.19"

[env]
_.python.venv = { path = ".venv" }

[settings]
lockfile_platforms = ["macos-arm64", "linux-x64"]

[settings.ruby]
compile = false
